# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      important:
        patterns:
          - "bc-*"
          - "@blockception*"
          - "vscode-*"
        exclude-patterns:
          - "node-fetch"
      nodejs:
        patterns:
          - "typescript"
          - "ts-*"
          - "@types/node"
          - "node"
          - "webpack"
          - "webpack-cli"
        exclude-patterns:
          - "node-fetch"
      test:
        patterns:
          - "jest"
          - "eslint"
          - "*eslint*"
          - "*jest*"
          - "@types/eslint"
          - "@types/jest"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "gitsubmodule"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    
