name: ğŸ“‘ Release Page

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: ğŸ“‘ Release Page
    runs-on: "ubuntu-latest"

    steps:
      - name: ğŸ“‘ Release Page
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ORBI_TOKEN }}"
          prerelease: false
